# Generated by Django 5.1.5 on 2025-01-27 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bhakti", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["category_name"]},
        ),
        migrations.AddField(
            model_name="information",
            name="heading",
            field=models.CharField(default="Bhakti Pravah", max_length=100),
        ),
        migrations.AlterField(
            model_name="information",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information",
                to="bhakti.category",
            ),
        ),
        migrations.AddField(
            model_name="information",
            name="title",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information",
                to="bhakti.title",
            ),
        ),
    ]
