# Generated by Django 5.1.5 on 2025-02-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bhakti", "0002_title_alter_category_options_information_heading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="upload/"),
        ),
    ]
