# Generated by Django 5.1.5 on 2025-02-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bhakti", "0003_alter_information_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="image",
            field=models.BinaryField(),
        ),
    ]
