# Generated by Django 5.1.5 on 2025-02-01 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bhakti", "0005_alter_information_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information",
                to="bhakti.category",
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="information",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information",
                to="bhakti.title",
            ),
        ),
    ]
