# Generated by Django 5.1.5 on 2025-02-01 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bhakti", "0006_alter_information_category_alter_information_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information",
                to="bhakti.category",
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="upload/"),
        ),
        migrations.AlterField(
            model_name="information",
            name="title",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information",
                to="bhakti.title",
            ),
        ),
    ]
