# Generated by Django 5.1.5 on 2025-02-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bhakti", "0007_alter_information_category_alter_information_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "information",
                    models.ManyToManyField(
                        blank=True, related_name="info_lists", to="bhakti.information"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
