# Generated by Django 5.1.5 on 2025-02-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bhakti", "0009_infolistinformation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="infolist",
            options={},
        ),
        migrations.DeleteModel(
            name="InfoListInformation",
        ),
    ]
