# Generated by Django 5.1.5 on 2025-02-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bhakti", "0011_infolistinformation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="title",
            options={},
        ),
    ]
