# Generated by Django 5.1.5 on 2025-02-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bhakti", "0012_alter_category_options_alter_title_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InfoListInformation",
        ),
    ]
