# Generated by Django 5.1.5 on 2025-02-03 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bhakti", "0013_delete_infolistinformation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infolist",
            name="information",
        ),
        migrations.AlterField(
            model_name="infolist",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name="InfoListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.PositiveIntegerField()),
                (
                    "info_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bhakti.infolist",
                    ),
                ),
                (
                    "information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bhakti.information",
                    ),
                ),
            ],
            options={
                "ordering": ["order_number"],
            },
        ),
    ]
