# Generated by Django 5.1.5 on 2025-02-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bhakti", "0014_remove_infolist_information_alter_infolist_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["category_name"]},
        ),
        migrations.AlterModelOptions(
            name="information",
            options={"ordering": ["category__category_name", "title__name", "heading"]},
        ),
        migrations.AlterModelOptions(
            name="title",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="information",
            name="image",
        ),
        migrations.AddField(
            model_name="information",
            name="image_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
